#!/usr/bin/env php
<?php declare(strict_types = 1);

require __DIR__ . '/vendor/autoload.php';

define('DATA_DIRECTORY', __DIR__ . '/data');

use Symfony\Component\Console\Application;

$container = new DI\Container();

$application = new Application();
$application->add($container->get('App\Command\CalculateVacationDaysCommand'));
$application->run();

