#!/usr/bin/env php
<?php declare(strict_types = 1);

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$builder = new DI\ContainerBuilder();
$builder->addDefinitions([
    Psr\Log\LoggerInterface::class => new Monolog\Logger(''),
]);

$container = $builder->build();

$application = new Application();
$application->add($container->get('App\Command\CalculateVacationDaysCommand'));
$application->run();

